### ISSUE TITLE
Failing unit tests

### ISSUE THREAD

**Issue by debalance** [processone/p1_oauth2#2]
Hi,
on a current Debian Sid with Erlang 20, p1_oauth2 now has several unit tests failing.
I can't make much sense of it, full build log is attached.
[erlang-p1-oauth2_0.6.1-4_amd64.build.txt](https://github.com/processone/p1_oauth2/files/1139858/erlang-p1-oauth2_0.6.1-4_amd64.build.txt)

**Comment by prefiks** [comment]
Should be fixed be https://github.com/processone/p1_oauth2/commit/6094bcf62af7ff720ff7b45f3574bcdf282fb9b5

**Comment by debalance** [comment]
Thx! Now I know that erlang-proper in Debian is too old and have opened https://bugs.debian.org/868659 accordingly.

**Comment by debalance** [comment]
With latest erlang-proper and erlang-meck and Erlang 20.0.1 I still have the same 2 unit tests failing,
the log looks just like the one provided in my original post.

**Comment by bowlofeggs** [comment]
I also observe these same two unit test failures with Erlang 20 on [Fedora 28 and Rawhide](https://bugzilla.redhat.com/show_bug.cgi?id=1560321).

**Comment by prefiks** [comment]
I removed code that used removed function and test that was testing it.

**Comment by bowlofeggs** [comment]
Thanks for the patch - I've imported it into Fedora 28 and Rawhide!
